- docs/rtd-requirements.txt
- requirements.txt
> Adds some missing requirements

- dias/task.py
> add task-failed metric: dias_failed_total

- dias/scheduler.py
> add task timeout metric: dias_timeouts_total

- dias/analyzers/thermaldata_analyzer.py
- dias/exception.py
Also implements it in thermaldata_analyzer.py
> Add DiasDataError exception.

- conf/tasks/feedpositions.conf
- dias/analyzers/feedpositions_analyzer.py
> feedpositions: make sources configurable and add VirA

- dias/task.py
> Fix random start times

- dias/analyzers/sensitivity_analyzer.py
There are minor edits of a possible bug (wrong error message) and the way timestamp is read for output file name.
> added database

- dias/analyzers/sensitivity_analyzer.py
The refresh database was trying to use undeclared `log` when trying to remove files from database. It has been changed to `self.logger.info`. Further, the database address is now `state_dir` instead of `write_dir`.
> Sensitivity db

- dias/analyzers/sensitivity_analyzer.py
Exports the average thermal noise estimate for both polarizations.
> Sensitivity metric

- conf/tasks/sensitivity.conf
- dias/analyzers/sensitivity_analyzer.py
Changed the cadence at which the analyzer queries for data from 24 hours to 2 hours. This would distribute the metrics exported to Grafana.
> Sensitivity cadence

- dias/analyzers/thermaldata_analyzer.py
Bugs:
* One should always convert through the inputs, and not assume they are the same as the indices.  The chimetiming format changed so that data.input went from containing all inputs to containing only the ones involved in the NS system.
> Some fixes to get thermaldata sustainably working

- .travis.yml
- conf/tasks/source_spectra.conf
- dias/analyzers/__init__.py
- dias/analyzers/sensitivity_analyzer.py
- dias/analyzers/source_spectra_analyzer.py
- dias/utils/__init__.py
- dias/utils/helpers.py
- docs/user/analyzers.rst
- docs/user/dependencies.md
- setup.py
Making this PR on @saurabh-astro's behalf. Going to be reviewing and fixing it up.
The analyzer is perfectly functional / mergeable as-is, the improvements are all in the realm of code-quality.
From @saurabh-astro:
[The analyzer] is supposed to extract flux of a given source, as a function of frequency, when the source is right at the zenith. If the flux of the source is similar to what we expect from other measurements, our calibration is doing a good job!
Before merging:
From Saurabh wrt prometheus metrics:
```
I think prometheus metric would be great! May be peak flux of CygA for 4 frequencies
09:55
433.59375,558.203125,665.625,758.203125
09:55
These are referred to as N^2 frequencies, which are supposedly cleaner and not affected by RFI
```
> feat(source spectra): add analyzer

- conf/tasks/sensitivity.conf
This increases data size retention to 1 TB and state size retention to 1 GB.
> feat(sensitivity): increase sensitivity retention by a factor of 10

- conf/dias.conf
- conf/tasks/sensitivity.conf
- conf/tasks/thermaldata.conf
- dias/analyzer.py
- dias/analyzers/sensitivity_analyzer.py
- dias/analyzers/source_spectra_analyzer.py
- dias/analyzers/thermaldata_analyzer.py
- dias/chime_analyzer.py
- dias/config_loader.py
- dias/tracker.py
- test/test_tracker.py
Closes #145
I still need to add documentation for a green build, but it is ready to be looked at.
> feat(tracker): add interface to db tracking files processed by analyzers

- dias/analyzers/flag_rfi_analyzer.py
Since the addition of new noise source inputs, the representative
products used to label the stacked chime autocorrelations contain
noise source inputs.  The noise source inputs do not have polarisation
information, so attempting to determine the stack's polarisation raises
an error.  This commit redefines the representative products so that they
do not contain any non-sky inputs using the existing method
tools.redefine_stack_index_map.
> fix(flag_rfi_analyzer): use tools.redefine_stack_index_map

- dias/config_loader.py
- dias/utils/tracker.py
- test/test_tracker.py
Read-only mode is required for tracker to be used in theremin.
Additionally fixes bug in peewee time range queries.
> feat(tracker): create a read-only mode for tracker and bug fix

- dias/analyzers/dataset_analyzer.py
```
[2021-01-20 00:36:04,563] dias[dataset]: Found 1 acqws in flags files
[2021-01-20 00:36:04,630] dias[dataset]: Now processing acquisition /mnt/gong/staging/20210101T000000Z_chime_flaginput (7 files)
[2021-01-20 00:36:20,848] dias[dataset]: Flags don't match for dataset 486a4c7d20d88785bbbf2fdf92e3b517 (b'flaginput_20210112T131136.172720Z_rfi') between the following files:
- '/mnt/gong/staging/20201223T011000Z_chimestack_corr/01766367_0000.h5'
- '/mnt/gong/staging/20210101T000000Z_chime_flaginput/' 
[2021-01-20 00:36:20,848] dias[dataset]: Flags in 1/12 frames mismatch.
[2021-01-20 00:36:20,848] dias[dataset]: Flags for 1 inputs mismatch:
[2021-01-20 00:36:20,856] dias[dataset]: Input (1436, 'FCC040300') mismatches in 1/12 frames
[2021-01-20 00:36:20,856] dias[dataset]: The input is …
```
> feat(dataset_analyzer): improve logging

- dias/analyzers/source_spectra_analyzer.py
> fix(source_spectra): clean-up logging; use f-strings, move relevant statements to debug

- dias/scheduler.py
- dias/task.py
Related to https://github.com/chime-experiment/ch_ansible/pull/261
> fix(metrics): prometheus_client Counter automatically adds Total as a suffix

- dias/analyzers/dataset_analyzer.py
Dataset analyzer removes null dataset ids from its checks. It is important to check that null dataset ids are correctly assigned first.
This test results in `210212T193914Z_chimestack_corr/02015525_0000.h5` passing and `20210321T130426Z_chimestack_corr/00086522_0000.h5` failing.
Do we want to add more in-depth logging? List of dataset ids that failed the test, or the number of them that failed? Would that be helpful?
> feat(dataset): check that there are not valid frames with null dataset ids

- .github/workflows/main.yml
- dias/analyzers/sensitivity_analyzer.py
- dias/analyzers/source_spectra_analyzer.py
- dias/utils/string_converter.py
> fix(sensitivity): Skip files with timestamp[0] == NaN
