chime-experiment/dias

dias/analyzers/flag_rfi_analyzer.py
fixes #80 
When dias gets the task option to run a task when the last scheduled one is still running, we have to fix this, either
- Access to the connection has to be synchronized
or
- Forbid the option in this analyzer
=> FlagRFIAnalyzer: Allow sqlite connection access from task threads

.travis.yml
Running the configtest should find missing requirements, since it will
import all analyzers. It should also check task yaml file syntax.
=> CI: run scripts/dias configtest

dias/config_loader.py
Ref: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
=> Use pyyaml.safe_load to avoid deprecation warning (#87)

dias/task.py
This metric gets incremented in case tasks fail with DiasDataError.
All other excetptions in tasks still result in dias_task_failed_total.
Closes #96
=> feat(task): Add metric dias_task_no_data_total

dias/utils/string_converter.py
I now get from `python setup.py egg_info` (via `pip install`):
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-7V7haW/dias/setup.py", line 10, in <module>
import dias
File "dias/__init__.py", line 4, in <module>
from .analyzer import Analyzer
File "dias/analyzer.py", line 4, in <module>
from dias.utils import str2timedelta, str2datetime, str2bytes
File "dias/utils/__init__.py", line 2, in <module>
from .string_converter import *
File "dias/utils/string_converter.py", line 210
SyntaxError: Non-ASCII character '\xe2' in file dias/utils/string_converter.py on line 211, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
That non-ASCII character's been around for months.  Not sure why this hasn't happened before.
=> doc: replace non-ASCII character

setup.py
It creates a Catch-22: pip can't figure out the dependencies
because it can't run setup.py until the dependencies are installed.
=> fix(setup.py): Don't import dias in setup.py

dias/analyzers/sensitivity_analyzer.py
The units in the metrics were in mJy, while the labels showed uJy. The units in the metric have been changed to uJy. Also, polarization for EW was selecting both the polarizations.
=> bug fix in average sensitivity metric

dias/analyzers/flag_rfi_analyzer.py
flag_rfi_analyzer reached data size limit.  Dias started deleting old files,
which exercised a previously unused part of the code and encountered this
typo.
=> fix(flag_rfi_analyzer): fixes typo log --> logger.

conf/tasks/find_jump.conf, conf/tasks/flag_rfi.conf, dias/analyzers/find_jump_analyzer.py, dias/analyzers/flag_rfi_analyzer.py
Moves all database files for the flag_rfi_analyzer and find_jump_analyzer
from the data directory to the state directory.  Also changes the
archive_data_dir for the find_jump_analyzer from the deprecated
/mnt/gong/not_archived to /mnt/gong/staging.
Closes Issue #97 and Issue #99.
=> fix(flag_rfi,find_jump): save all database files in the state directory

dias/analyzer.py
This should fix the problem where the dias task automation was not detecting that files in the specified time range were actually available.
=> fix: we were missing the information about the timerange contained in the filename

dias/analyzers/find_jump_analyzer.py
=> fix(find_jump): check for empty query results

dias/analyzers/thermaldata_analyzer.py
Addresses
```
AlertManagerAPP 09:17
dias no data. (marimba:4444)  - WARNING
The dias task thermaldata can't find any data. If this is expected, silence this alert until there should be data again.
Anja Boskovic 10:21
Dec 16 09:13:17 marimba dias[20040]: [2019-12-16 17:13:17,140] dias[thermaldata]: Task failed: 'str' object has no attribute 'as_loaded_data'
Dec 16 09:13:17 marimba dias[20040]: [2019-12-16 17:13:17,450] dias[thermaldata]: Traceback (most recent call last):
Dec 16 09:13:17 marimba dias[20040]:   File "/usr/local/lib/python3.5/dist-packages/dias/task.py", line 229, in runner
Dec 16 09:13:17 marimba dias[20040]:     result = self.analyzer.run()
Dec 16 09:13:17 marimba dias[20040]:   File "/usr/local/lib/python3.5/dist-packages/dias/analyzers/thermaldata_analyzer.py", line 135, …
```
=> fix(thermaldata): expects a data-interval for an acquisition, not a filename

conf/tasks/sensitivity.conf
Given we have data back to february now, this should give us something like two years of look-back.
=> conf(sensitivity): 10x data storage size

dias/task.py
The `dias_data_...` metric namespace is meant to be for data metrics written by analyzers, not housekeeping information.  This renames the housekeeping metric `dias_data_written_bytes` to `dias_total_data_written_bytes` to move it out of the `dias_data` namespace.
=> fix(task): rename metric

dias/analyzers/find_jump_analyzer.py
```
y 03 23:57:07 marimba dias[6884]:   File "/usr/local/lib/python3.7/dist-packages/dias/analyzers/find_jump_analyzer.py", line 1125, in run                                  
May 03 23:57:07 marimba dias[6884]:     srchd.create_dataset("input", data=this_input[ifeed])                                                                                
May 03 23:57:07 marimba dias[6884]:   File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/group.py", line 136, in create_dataset                                           
May 03 23:57:07 marimba dias[6884]:     dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)                                                                       
May 03 23:57:07 marimba dias[6884]:   File …
```
=> fix(find_jump): add workaround for h5py not supporting dtype <U32

setup.py
- we previously used --install-options when installing dias
- bc of this pip bug https://github.com/pypa/pip/issues/1883, we cannot
use that option in the same install command
- sister PR https://github.com/chime-experiment/ch_ansible/pull/91
=> build: move installation of task configs to ch_ansible

dias/analyzers/source_spectra_analyzer.py
A bug fix, where start and stop times for each file is used to determine number of time frames to be read. Since `time_delta` is specified in the `Finder`, current fix is simply using the start and end times of the files listed by `Finder`. In future, we may want a more careful selection of frames based on the span of source in a given file.
=> fix number time frames

dias/tracker.py, test/test_tracker.py
- replace is a conflict resolution strategy that does not involve
force-inserting duplicates or IntegrityErrors
- conflicts result when multiple analyzers are trying to perform
updating actions to the same db simultaneously
=> fix(tracker): inserts should use a replace conflict resolution strategy

dias/analyzers/sensitivity_analyzer.py
This means if sensitivity is interrupted, it does not do everything from
scratch again.
=> fix(sensitivity): register files as processed, as they are processed

dias/analyzers/dataset_analyzer.py
The first bug came up when the tracker found multiple flaginput acquisitions within a timeframe.
It would only validating flags in the most recent acquisition, instead of in all of them, bc of me accidentally putting `flg = dict()` within the acquisition loop.
(This is the source of the new "Flag IDs not found" bug.)
The second bug was that Ia Unix timestamp float was being compared with a datetime object.
=> Two bugfixes

dias/analyzers/dataset_analyzer.py
This change has been tested.
Closes #174
=> fix(dataset): skip initial_flags updates; they do not exist in flaginput files

dias/analyzers/daily_ringmaps.py
h5py version 3 switched the default file open to be `r` instead of `w+`
=> fix(ringmaps): be explicit about requiring write permissions for file

dias/chime_analyzer.py, dias/config_loader.py, dias/utils/string_converter.py
It's a bit weird that we allow path expansion on `task_write_dir` and `task_state_dir` but not `archive_data_dir` nor `staging_data_dir`.
Closes #179
=> fix(dias): complain on missing directory

dias/chime_analyzer.py
I should have though a bit longer about that thing I thought was odd in the previous PR.
Those lines don't set the value; they just define the prototype for the Property.
Have deployed this.  It is running.
=> fix(chime_analyzer): Properly check for missing directory

conf/tasks/feedpositions.conf, dias/analyzers/feedpositions_analyzer.py
It is not considered useful anymore, and was starting to bug up a bit. We decided to not continue maintaining it.
=> feat: remove feedpositions from being scheduled by dias

dias/analyzers/dataset_analyzer.py
- when flag updates are resent (which can happen during heat-related
correlator shut-downs) that flag
update was from before the correlator shutdown, but can end up in the
chimestack file for the next UTC day.
- this change additionally checks day-old flaginput files to validate flag update ids
- this change also adds a metric `updateid_not_found` that is augmented when update ids are not found in the available flaginput files
Closes #196
=> fix(dataset): additionally check day-old flag files for update ids

.github/workflows/main.yml, dias/__init__.py, dias/analyzer.py, dias/analyzers/__init__.py, dias/analyzers/daily_ringmaps.py, dias/analyzers/feedpositions_analyzer.py, dias/analyzers/find_jump_analyzer.py, dias/analyzers/flag_rfi_analyzer.py, dias/analyzers/sample_analyzer.py, dias/analyzers/sensitivity_analyzer.py, dias/analyzers/test_analyzer.py, dias/config_loader.py, dias/job.py, dias/scheduler.py, dias/task.py, dias/task_queue.py, dias/utils/__init__.py, dias/utils/string_converter.py
`sensitivity_analyzer.py` has the only substantive change.  It was still using `iteritems` instead of `items`, presumably in some code that's rarely exercised or we'd have found this earlier.
I've patched this in-place on marimba.
Also re-blackened.
=> fix(sensitivity): Fix `items` call in sensitivity analyser

.github/workflows/main.yml, dias/utils/tracker.py, test/test_tracker.py
Such files will be completely skipped by the tracker, as if they didn't exist on disk.
Locked files are ones for which a .<name>.lock file exists.
=> fix(tracker): Skip locked files

.github/workflows/main.yaml
The doc build is broken and the doc build check in the CI is already disabled.
=> ci: Don't install doc requirements

dias/analyzers/flag_rfi_analyzer.py
The Finder crashes with a ValueError when given a non-positive time range.
=> fix(flag_rfi): Don't give finder invalid interval
